services:
  # API - DenoJS
  backend:
    build: ./api
    container_name: furia-backend
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - postgres
      - mongo

  # FRONTEND - Bun + SolidJS (Vite)
#  frontend:
#    build: ./web
#    container_name: furia-frontend
#    ports:
#      - "5173:5173"
#    env_file:
#      - ./web/.env
#    volumes:
#      - ./web:/app
#    working_dir: /app
#   command: ["bun", "run", "dev", "--", "--host"]

  # PostgreSQL - Banco relacional
  postgres:
    image: postgres:16
    container_name: furia-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: furia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: furia_users
    volumes:
      - pg_data:/var/lib/postgresql/data

  # MongoDB - Banco documental
  mongo:
    image: mongo:6
    container_name: furia-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
